jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${ADMIN_USERNAME}"
          password: "${ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false