---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vote-service-hpa
  namespace: vote-poll
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: vote-poll
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poll-service-hpa
  namespace: vote-poll
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poll-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
